# Generated by Django 5.2.8 on 2025-12-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='customer',
        ),
    ]
